Role system and a little  bit of cleanup
SOQSoft/Festispec.App pull request #16
Opened 2018-11-18 20:24 UTC by OhMyGuus

## Samenvatting

* Role systeem gemaakt via een enum
* Een klein beetje cleanup toegepast komt nog meer in een andere pr

Fixes SOQSoft/Festispec.Project#19

2018-11-18 22:27 UTC, bahfheuv requested changes

2018-11-18 22:27 UTC, bahfheuv commented on Fesispec.Domain/Roles.cs
> +        User,
Ik zou hier Manager, Inspector, Advisor, Salesemployee, Planner doen... Je wil niet dat een inspecteur ook ff klanten kan toevoegen of dat een Salesemployee op de Inspecteurs web app kan inloggen.

2018-11-18 22:27 UTC, bahfheuv commented on Fesispec.Domain/Role.cs
> +        public Roles Roles { get; set; } = Roles.User;
Is dit niet dubbel?
Roles Role {get;}
public Role(string roles) {
 Role = RolesExtension.ToString(string)
}

Rol zal namelijk via string binnenkomen. Daar moet het in de juiste Roles worden omgezet.
Setter hoeft niet, is statisch

2018-11-18 22:27 UTC, bahfheuv commented on Festispec.App/ViewModels/LoginViewModel.cs
> +        public string Password { get; set; }
De rede voor het vorige uitgebreide was vgm dat er RaisePropertyChanged aangeroepen moest worden, zul je moeten navragen aan Simon.

2018-11-18 22:27 UTC, bahfheuv commented on Festispec.App/ViewModels/UserViewModel.cs
> +        [PreferredConstructor]
Wat is dit dingetje?

2018-11-18 22:58 UTC, OhMyGuus commented on Fesispec.Domain/Role.cs
> +        public Roles Roles { get; set; } = Roles.User;
Setter is nodig voor EF

2018-11-18 23:00 UTC, OhMyGuus commented on Fesispec.Domain/Roles.cs
> +        User,
We hebben alleen maar Manager en Inspecteur roles had het maar User en admin genoemd leekt mij handiger voor de app.

2018-11-18 23:03 UTC, OhMyGuus commented on Festispec.App/ViewModels/UserViewModel.cs
> +        [PreferredConstructor]
Dat is nodig voor DI want die weet natuurlijk niet welke constructor hij moet pakken

2018-11-18 23:05 UTC, OhMyGuus commented on Festispec.App/ViewModels/LoginViewModel.cs
> +        public string Password { get; set; }
Zodra Simon dat toevoegd krijgt hij de optie op zijn versie te gebruiken (bij een merge). 
Op dit moment was dit nog niet het geval.

2018-11-18 23:06 UTC, OhMyGuus commented on Fesispec.Domain/Roles.cs
> +        User,
Maar  kan er wel meerdere dingen van maken is in princiepe niet veel werk moeten morgen even herdenken welke rollen er nodig zijn

2018-11-19 12:18 UTC, bahfheuv approved these changes

2018-11-19 12:18 UTC, merged